import { Quiz } from '../types';
import { ArrowLeft, Printer } from 'lucide-react';

interface PrintViewProps {
  quiz: Quiz;
  onBack: () => void;
}

export default function PrintView({ quiz, onBack }: PrintViewProps) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* Controls - Hidden when printing */}
      <div className="mb-6 flex items-center justify-between print:hidden">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-4 py-2 text-gray-700 hover:text-indigo-600 hover:bg-gray-100 rounded-lg transition-colors"
        >
          <ArrowLeft size={20} />
          Back to Results
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium"
        >
          <Printer size={20} />
          Print Worksheet
        </button>
      </div>

      {/* Printable Worksheet */}
      <div className="bg-white p-8 print:p-0 print:bg-white">
        {/* Header */}
        <div className="border-b-2 border-gray-900 pb-4 mb-6">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            {quiz.chapterTitle}
          </h1>
          <div className="flex justify-between items-center text-sm text-gray-700">
            <div>
              <p className="font-semibold">Subject: {quiz.subject}</p>
              <p>Multiple Choice Quiz</p>
            </div>
            <div className="text-right">
              <p>Name: _________________________</p>
              <p className="mt-1">Date: _________________________</p>
            </div>
          </div>
        </div>

        {/* Instructions */}
        <div className="mb-6 p-4 bg-gray-50 border border-gray-300 rounded">
          <p className="text-sm text-gray-800">
            <strong>Instructions:</strong> Read each question carefully. Circle the letter of the best answer. 
            Each question has only one correct answer.
          </p>
        </div>

        {/* Questions */}
        <div className="space-y-6">
          {quiz.questions.map((question, index) => (
            <div key={question.id} className="break-inside-avoid">
              {/* Question */}
              <div className="mb-3">
                <p className="text-base font-semibold text-gray-900">
                  <span className="text-gray-600 mr-2">{index + 1}.</span>
                  {question.question}
                </p>
              </div>

              {/* Answer Choices */}
              <div className="ml-6 space-y-2">
                {question.options.map((option, optIndex) => {
                  const letter = String.fromCharCode(65 + optIndex); // A, B, C, D
                  return (
                    <div key={optIndex} className="flex items-start gap-2">
                      <span className="font-semibold text-gray-700 min-w-[20px]">
                        {letter})
                      </span>
                      <span className="text-gray-800 flex-1">{option}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-gray-300">
          <div className="flex justify-between items-center text-xs text-gray-600">
            <p>Generated by QuizForge</p>
            <p>{quiz.questions.length} Questions</p>
          </div>
        </div>
      </div>

      {/* Answer Key - Separate Page */}
      <div className="mt-12 bg-white p-8 print:p-0 print:bg-white print:mt-0 print:break-before-page">
        <div className="border-b-2 border-gray-900 pb-4 mb-6">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Answer Key</h2>
          <p className="text-sm text-gray-700">{quiz.chapterTitle} - {quiz.subject}</p>
          <p className="text-xs text-red-600 mt-2 font-semibold">
            ⚠️ TEACHER COPY - DO NOT DISTRIBUTE TO STUDENTS
          </p>
        </div>

        {/* Answer Grid */}
        <div className="mb-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-3">Quick Reference</h3>
          <div className="grid grid-cols-5 gap-3 text-sm">
            {quiz.questions.map((question, index) => {
              const letter = String.fromCharCode(65 + question.correctAnswer);
              return (
                <div key={question.id} className="flex items-center gap-2">
                  <span className="font-semibold text-gray-700">{index + 1}.</span>
                  <span className="px-2 py-1 bg-green-100 text-green-800 rounded font-bold">
                    {letter}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Detailed Answers */}
        <div>
          <h3 className="text-lg font-semibold text-gray-900 mb-3">Detailed Answers</h3>
          <div className="space-y-4">
            {quiz.questions.map((question, index) => {
              const correctLetter = String.fromCharCode(65 + question.correctAnswer);
              return (
                <div key={question.id} className="break-inside-avoid">
                  <div className="mb-2">
                    <p className="text-sm font-semibold text-gray-900">
                      <span className="text-gray-600 mr-2">{index + 1}.</span>
                      {question.question}
                    </p>
                  </div>
                  <div className="ml-6 space-y-1">
                    <p className="text-sm text-gray-800">
                      <span className="font-bold text-green-700">Correct Answer: {correctLetter})</span>{' '}
                      {question.options[question.correctAnswer]}
                    </p>
                    {question.explanation && (
                      <p className="text-xs text-gray-600 mt-1">
                        <span className="font-semibold">Explanation:</span> {question.explanation}
                      </p>
                    )}
                    {question.sourceText && (
                      <p className="text-xs text-gray-500 mt-1 italic">
                        Source: "{question.sourceText}"
                      </p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Grading Notes */}
        <div className="mt-8 pt-6 border-t border-gray-300">
          <h3 className="text-lg font-semibold text-gray-900 mb-3">Grading Notes</h3>
          <ul className="text-sm text-gray-700 space-y-2 list-disc list-inside">
            <li>Total Questions: {quiz.questions.length}</li>
            <li>Points per Question: _____ (fill in)</li>
            <li>Total Points: _____ (fill in)</li>
            <li>Student Score: _____ / _____</li>
            <li>Percentage: _____%</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
