import { useState } from 'react';
import { Quiz } from '../types';
import { ArrowLeft, Printer, Eye } from 'lucide-react';

interface PrintViewProps {
  quiz: Quiz;
  onBack: () => void;
}

export default function PrintView({ quiz, onBack }: PrintViewProps) {
  const [showAnswerKey, setShowAnswerKey] = useState(false);

  return (
    <div className="space-y-6">
      {/* Controls */}
      <div className="flex items-center justify-between no-print">
        <div className="flex items-center gap-3">
          <button onClick={onBack} className="btn-ghost p-2"><ArrowLeft className="w-5 h-5" /></button>
          <div>
            <h1 style={{ color: 'var(--text-primary)' }}>Print Preview</h1>
            <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Preview and print your worksheet</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => setShowAnswerKey(!showAnswerKey)} className={`btn-secondary ${showAnswerKey ? 'ring-2' : ''}`} style={showAnswerKey ? { borderColor: 'var(--emerald)' } : {}}>
            <Eye className="w-4 h-4" /> {showAnswerKey ? 'Hide' : 'Show'} Key
          </button>
          <button onClick={() => window.print()} className="btn-primary"><Printer className="w-4 h-4" /> Print</button>
        </div>
      </div>

      {/* Printable Quiz */}
      <div className="glass-card-static print:shadow-none print:border-none" style={{ background: '#fff', color: '#000' }}>
        <div className="p-8 print:p-4">
          <div className="border-b-2 border-gray-800 pb-4 mb-6">
            <div className="flex justify-between items-start">
              <div>
                <h1 className="text-2xl font-bold text-gray-900">{quiz.chapterTitle}</h1>
                <p className="text-gray-600 mt-1">Subject: {quiz.subject}</p>
                <p className="text-gray-600 text-sm">Multiple Choice • {quiz.questions.length} Questions</p>
              </div>
              <div className="text-right text-sm text-gray-600">
                <p>Date: _______________</p>
                <p className="mt-1">Name: _______________</p>
                <p className="mt-1">Score: _____ / {quiz.questions.length}</p>
              </div>
            </div>
          </div>

          <div className="mb-6 p-3 bg-gray-50 rounded-lg text-sm text-gray-700">
            <strong>Instructions:</strong> Circle the letter of the best answer for each question.
          </div>

          <div className="space-y-6">
            {quiz.questions.map((question, qIndex) => (
              <div key={question.id} className="break-inside-avoid">
                <p className="font-medium text-gray-900 mb-2">
                  <span className="text-gray-500">{qIndex + 1}.</span> {question.question}
                </p>
                <div className="ml-6 space-y-1">
                  {question.options.map((option, oIndex) => (
                    <div key={oIndex} className="flex items-start gap-2 text-gray-700">
                      <span className="font-medium min-w-[20px]">{String.fromCharCode(65 + oIndex)})</span>
                      <span>{option}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
            Generated by QuizForge • {new Date(quiz.createdAt).toLocaleDateString()}
          </div>
        </div>
      </div>

      {/* Answer Key */}
      {showAnswerKey && (
        <div className="glass-card-static print:shadow-none print:border-none print:break-before-page" style={{ background: '#fff', color: '#000' }}>
          <div className="p-8 print:p-4">
            <div className="border-b-2 border-gray-800 pb-4 mb-6">
              <h2 className="text-xl font-bold text-gray-900">Answer Key</h2>
              <p className="text-gray-600 text-sm">{quiz.chapterTitle} • {quiz.subject}</p>
              <p className="text-xs text-red-600 font-medium mt-1">⚠ Instructor Copy</p>
            </div>

            <div className="mb-6 p-4 bg-gray-50 rounded-lg">
              <div className="grid grid-cols-5 md:grid-cols-10 gap-2">
                {quiz.questions.map((q, i) => (
                  <div key={q.id} className="text-center text-sm">
                    <span className="text-gray-500">{i + 1}.</span>
                    <span className="font-bold text-gray-900 ml-1">{String.fromCharCode(65 + q.correctAnswer)}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              {quiz.questions.map((q, i) => (
                <div key={q.id} className="text-sm">
                  <span className="text-gray-500">{i + 1}.</span>{' '}
                  <span className="font-bold text-green-700">{String.fromCharCode(65 + q.correctAnswer)}) {q.options[q.correctAnswer]}</span>
                  {q.explanation && <span className="text-gray-500 text-xs ml-2">— {q.explanation}</span>}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
